import Head from "next/head";
import { useState } from "react";
import FeaturedProjects from "../components/FeaturedProjects";

export default function Home() {
  const [projects, setProjects] = useState([
    {
      id: 1,
      name: "",
      segment: "",
      description: "",
      link: "",
      sourceCode: "",
      image: "",
    },
    {
      id: 2,
      name: "Moovtime",
      segment: "Online Streaming movies/series platform",
      description:
        "A streaming platform that provides movies & series having the account access. Sign In, Sign up, Browse, Auth listeners, Protected routes.",
      link: "https://moovtime.netlify.app",
      sourceCode: "https://github.com/Oliverhf/moovtime",
      image:
        "https://res.cloudinary.com/dakam7rfa/image/upload/v1655426377/Captura_de_Tela_2022-06-16_a%CC%80s_21.36.55_kudis2.png",
    },
    {
      id: 3,
      name: "RecipeApp",
      segment: "Blog/Social",
      description:
        "Recipes from different chefs in one place, providing diversity in cuisine and its sharing. Posts, PostDetails, Author and AuthorDetails.",
      link: "https://recipe-app-gamma-five.vercel.app/",
      sourceCode: "https://github.com/Oliverhf/recipe-app",
      image:
        "https://res.cloudinary.com/dakam7rfa/image/upload/v1655426389/Captura_de_Tela_2022-06-16_a%CC%80s_21.37.24_rdgied.png",
    },
  ]);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="relative max-h-full">
        <div>
          <div className="relative">
            <img
              className="relative w-screen inset-0 z-10 grayscale-[70%]"
              src="https://res.cloudinary.com/dakam7rfa/image/upload/v1655332291/bg-web_lrxacf.jpg"
            />
            <div
              style={{
                background: "linear-gradient(45deg, #000401, transparent)",
              }}
              className="absolute z-20 inset-0 block"
            >
              <div className="m-40">
                <h1 className="block m-10 text-6xl font-bold text-white text-center">
                  Oliver <span className="text-blue">Favalli</span>
                </h1>
                <p className="block m-10 text-xl font-normal text-white text-center">
                  São Paulo, Brazil{" "}
                  <span className="font-light opacity-70 mx-1">|</span> +55 11
                  97555-8597
                </p>
                <span className="block text-white text-center text-gray">
                  Challenge-driven software developer.
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="relative h-screen">
        <div className="py-32">
          <h2 className="text-blue text-4xl text-center font-normal uppercase leading-12">
            Projects
          </h2>
          <hr className="block rounded-md w-8 h-2 m-auto my-12"></hr>
          <div className="flex justify-evenly container mx-auto px-10 mb-8">
            {projects.map((project) => (
              <FeaturedProjects key={project.id} project={project} />
            ))}
          </div>
        </div>
      </section>
      <section className="relative h-100 rounded-sm">
        <div className="relative py-4 mb-16 bg-blue">
          <div>
            <h4 className="text-white text-4xl text-center uppercase font-normal leading-14">
              Skills
            </h4>
          </div>
        </div>
        <div className="container mx-auto px-10 mb-8 z-20">
          <div className="">
            <h5 className="text-black text-2xl capitalize font-normal">
              Programming Languages + Tools
            </h5>
            <div className="flex my-8 gap-2">
              <img
                align="center"
                alt="Oliver-HTML"
                height="30"
                width="40"
                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg"
              />
              <img
                align="center"
                alt="Oliver-CSS"
                height="30"
                width="40"
                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg"
              />
              <img
                align="center"
                alt="Oliver-SASS"
                height="30"
                width="40"
                src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg"
              />
              <img
                align="center"
                alt="Oliver-Js"
                height="30"
                width="40"
                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-plain.svg"
              />
              <img
                align="center"
                alt="Oliver-React"
                height="30"
                width="40"
                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg"
              />
              <img
                align="center"
                alt="Oliver-Redux"
                height="30"
                width="40"
                src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg"
              />
              <img
                align="center"
                alt="Oliver-NextJS"
                height="30"
                width="40"
                src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg"
              />
              <img
                align="center"
                alt="Oliver-Jest"
                height="30"
                width="40"
                src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg"
              />
              <img
                align="center"
                alt="Oliver-Node"
                height="30"
                width="40"
                src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg"
              />
              <img
                align="center"
                alt="Oliver-Csharp"
                height="30"
                width="40"
                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/csharp/csharp-original.svg"
              />
              <img
                align="center"
                alt="Oliver-Elixir"
                height="30"
                width="40"
                src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elixir/elixir-original.svg"
              />
              <img
                align="center"
                alt="Oliver-GraphQL"
                height="30"
                width="40"
                src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg"
              />
              <img align="center" alt="Oliver-PostgreSQL" height="30" width="40"src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg" />
              <img align="center" alt="Oliver-Firebase" height="40" width="50" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain-wordmark.svg" />
            </div>
            <div className="mb-20">
              <h5 className="text-black text-2xl my-8 capitalize font-normal">
                Workflow
              </h5>
              <div>
                <div>
                  <div className="flex items-center">
                    <div className="flex items-center mr-3">
                      <input 
                        className="flex items-center mr-2 accent-blueSecondary"
                        type="checkbox"
                        defaultChecked={true}
                      />
                      <span>React</span>
                    </div>
                    <div className="flex items-center mr-3">
                      <input 
                        className="flex items-center mr-2 accent-blueSecondary"
                        type="checkbox"
                        defaultChecked={true}
                      />
                      <span>NextJS</span>
                    </div>
                    <div className="flex items-center mr-3">
                      <input 
                        className="flex items-center mr-2 accent-blueSecondary"
                        type="checkbox"
                        defaultChecked={true}
                      />
                      <span>ASP.NET Web API</span>
                    </div>
                    <div className="flex items-center mr-3">
                      <input 
                        className="flex items-center mr-2 accent-blueSecondary"
                        type="checkbox"
                        defaultChecked={true}
                      />
                      <span>Express</span>
                    </div>
                    <div className="flex items-center mr-3 accent-blueSecondary">
                      <input 
                        className="flex items-center mr-2"
                        type="checkbox"
                        defaultChecked={true}
                      />
                      <span>Pheonix</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
